import Link from "next/link";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/form-controls";
import { FinanceReadService } from "@/server/finance/finance-read-service";
import {
  CancelManualFinanceForm, FinanceAccountForm, FinanceCategoryForm, FinanceTransferForm, ManualFinanceEntryForm,
  ReverseSettlementForm, SettleObligationForm,
} from "@/features/finance/finance-forms";
import { SupplierPaymentTermForm } from "@/features/finance/supplier-term-form";
import styles from "./finance-panel.module.css";

type SearchParams=Promise<{ from?:string;to?:string }>;
type Account={ id:string;name:string;account_type:string;system_key:string|null;balance_cents:number|string };
type Report={ period:{from:string;to:string;today:string;timezone:string}; accounts:Account[]; obligations:{receivable_open_cents:number|string;payable_open_cents:number|string;receivable_overdue_cents:number|string;payable_overdue_cents:number|string;open_count:number|string}; dre:{gross_revenue:number|string;deductions:number|string;delivery_revenue:number|string;cogs:number|string;operating_expense:number|string;other_revenue:number|string;other_expense:number|string;net_result:number|string}; cashflow:{net_realized_cents:number|string;daily:Array<{day:string;net_cents:number|string}>} };
const statusLabel:Record<string,string>={open:"Em aberto",partially_settled:"Parcial",settled:"Liquidado",cancelled:"Cancelado"};
function brl(cents:number|string|null|undefined){return new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(Number(cents??0)/100)}
function date(value:string|null|undefined){if(!value)return "—";const[y,m,d]=value.slice(0,10).split("-");return y&&m&&d?`${d}/${m}/${y}`:value}
function sourceLabel(source:string|null){const labels:Record<string,string>={order:"Venda",purchase_receipt:"Compra",supplier_credit:"Crédito fornecedor",manual:"Manual"};return source?labels[source]??source:"Manual"}
function accountTypeLabel(type:string){return({cash:"Dinheiro",bank:"Banco",clearing:"Liquidação",wallet:"Carteira",other:"Outra"}as Record<string,string>)[type]??type}

export default async function FinancePage({searchParams}:{searchParams:SearchParams}){
  const query=await searchParams;
  const data=await FinanceReadService.load({from:query.from??null,to:query.to??null});
  const report=(data.report??null) as Report|null;
  const accounts=data.accounts as Account[];
  const open=data.obligations.filter((ob)=>ob.status==="open"||ob.status==="partially_settled");

  return <section className={styles.page}>
    <header className={styles.header}><div className={styles.headerCopy}><p className="muted">Gestão financeira</p><h1>Financeiro</h1><p className="muted">A operação gera os fatos; esta tela organiza obrigações, contas, liquidações, fluxo realizado e análise gerencial sem editar saldo diretamente.</p></div><div className={styles.links}><Link href="/caixa" className={styles.link}>Caixa físico</Link><Link href="/compras" className={styles.link}>Compras</Link><Link href="/dashboard" className={styles.link}>Dashboard →</Link></div></header>

    {data.canReports&&report?<>
      <form method="get" className={`card ${styles.period}`}><Input label="De" name="from" type="date" defaultValue={data.period.from}/><Input label="Até" name="to" type="date" defaultValue={data.period.to}/><Button type="submit">Aplicar período</Button><span className={styles.periodHint}>DRE por competência · fluxo por liquidação · {data.store.timezone}</span></form>
      <div className={styles.metrics}><Metric label="Resultado DRE" value={brl(report.dre.net_result)} tone={Number(report.dre.net_result)<0?"bad":"good"}/><Metric label="Fluxo realizado" value={brl(report.cashflow.net_realized_cents)}/><Metric label="A receber" value={brl(report.obligations.receivable_open_cents)} warning={Number(report.obligations.receivable_overdue_cents)>0}/><Metric label="A pagar" value={brl(report.obligations.payable_open_cents)} warning={Number(report.obligations.payable_overdue_cents)>0}/></div>
      <div className={styles.reportGrid}><article className={`card ${styles.card}`}><h2>DRE gerencial</h2><Rows rows={[["Receita bruta",report.dre.gross_revenue],["Deduções e reembolsos",report.dre.deductions],["Receita de entrega",report.dre.delivery_revenue],["CPV",report.dre.cogs],["Despesas operacionais",report.dre.operating_expense],["Outras receitas",report.dre.other_revenue],["Outras despesas",report.dre.other_expense]]}/><div className={`${styles.row} ${styles.total}`}><span>Resultado</span><span>{brl(report.dre.net_result)}</span></div></article><article className={`card ${styles.card}`}><h2>Vencimentos</h2><Rows rows={[["Recebíveis em aberto",report.obligations.receivable_open_cents],["Recebíveis vencidos",report.obligations.receivable_overdue_cents],["Pagáveis em aberto",report.obligations.payable_open_cents],["Pagáveis vencidos",report.obligations.payable_overdue_cents]]}/><p className="muted">Vencido é leitura derivada da data local; o ledger histórico não é reescrito.</p></article></div>
    </>:<article className={`card ${styles.card}`}><h2>Visão operacional</h2><p className="muted">Sem `finance.reports`, DRE e fluxo ficam ocultos; obrigações e movimentos autorizados continuam visíveis.</p></article>}

    <div><div className={styles.headerCopy}><h2>Contas</h2><p className="muted">Saldos consolidados por conta; movimentações são feitas pelos fluxos abaixo.</p></div><div className={styles.accounts}>{accounts.map((account)=><article key={account.id} className={`card ${styles.account}`}><span className={styles.metricLabel}>{accountTypeLabel(account.account_type)}</span><strong>{account.name}</strong><strong className={`${styles.accountBalance} ${Number(account.balance_cents)<0?styles.negative:""}`}>{brl(account.balance_cents)}</strong>{account.system_key?<span className={styles.meta}>Conta técnica · {account.system_key}</span>:null}</article>)}</div></div>

    <article className={`card ${styles.card}`}><div><h2>Contas a receber e a pagar</h2><p className="muted">Compras, créditos e lançamentos manuais são liquidados aqui conforme permissão. Vendas continuam pelo módulo Pagamentos.</p></div>{open.length===0?<p className="muted">Nenhuma obrigação em aberto.</p>:<div className={styles.obligations}>{open.map((ob)=><div key={ob.id} className={styles.entry}><div className={styles.entryTop}><div><strong>{ob.description}</strong><div className={styles.meta}>{sourceLabel(ob.source_type)} · competência {date(ob.competence_date)} · vencimento {date(ob.due_date)}</div></div><div className={styles.entrySide}><strong className={ob.direction==="in"?styles.income:styles.expense}>{ob.direction==="in"?"A receber":"A pagar"} · {brl(ob.open_cents)}</strong><div className={styles.meta}>{statusLabel[ob.status]??ob.status} · principal {brl(ob.principal_cents)} · liquidado {brl(ob.settled_cents)}</div></div></div>{data.canSettle&&ob.source_type!=="order"?<details className={styles.details}><summary>Liquidar</summary><div className={styles.detailBody}><SettleObligationForm obligationId={ob.id} openCents={ob.open_cents} accounts={accounts}/></div></details>:null}{data.canManage&&ob.source_type==="manual"&&Number(ob.settled_cents)===0?<details className={styles.details}><summary>Cancelar lançamento manual</summary><div className={styles.detailBody}><CancelManualFinanceForm obligationId={ob.id}/></div></details>:null}</div>)}</div>}</article>

    {(data.canManage||data.canSettle)?<div className={styles.actionGrid}>{data.canManage?<article className={`card ${styles.card}`}><h2>Novo lançamento</h2><p className="muted">Competência afeta a DRE. Sem conta, o lançamento permanece como obrigação aberta.</p><ManualFinanceEntryForm categories={data.categories} accounts={accounts} today={data.period.today} canSettle={data.canSettle}/></article>:null}{data.canSettle?<article className={`card ${styles.card}`}><h2>Transferir entre contas</h2><p className="muted">Transferência é um par atômico e não entra na DRE.</p><FinanceTransferForm accounts={accounts}/></article>:null}{data.canManage?<article className={`card ${styles.card}`}><h2>Cadastros financeiros</h2><details className={styles.details}><summary>Criar conta</summary><div className={styles.detailBody}><FinanceAccountForm/></div></details><details className={styles.details}><summary>Criar categoria</summary><div className={styles.detailBody}><FinanceCategoryForm categories={data.categories}/></div></details></article>:null}</div>:null}

    {data.canManage&&data.suppliers.some((s)=>s.config?.active)?<article className={`card ${styles.card}`}><div><h2>Prazo financeiro de fornecedores</h2><p className="muted">Novos pedidos guardam o prazo como snapshot; compras antigas não são alteradas.</p></div><div className={styles.supplierGrid}>{data.suppliers.filter((s)=>s.config?.active).map((supplier)=><div key={supplier.id} className={styles.supplier}><strong>{supplier.name}</strong><SupplierPaymentTermForm supplierId={supplier.id} days={supplier.config?.payment_term_days??0}/></div>)}</div></article>:null}

    <article className={`card ${styles.card}`}><div><h2>Histórico de movimentos</h2><p className="muted">O ledger é imutável. Estorno cria novo lançamento e preserva o original.</p></div>{data.transactions.length===0?<p className="muted">Sem movimentos financeiros.</p>:<div className={styles.transactions}>{data.transactions.slice(0,80).map((tx)=><div key={tx.id} className={styles.entry}><div className={styles.entryTop}><span><strong>{tx.description||tx.transaction_type}</strong><span className={styles.meta}> · {tx.source_type||"financeiro"} · {new Date(tx.occurred_at).toLocaleString("pt-BR")}</span></span><strong className={tx.effect_sign<0?styles.negative:tx.direction==="in"?styles.income:styles.expense}>{tx.effect_sign<0?"estorno ":""}{tx.direction==="in"?"+":"−"}{brl(tx.amount_cents)}</strong></div>{data.canSettle&&tx.transaction_type==="settlement"&&(tx.source_type==="manual_settlement"||tx.source_type==="manual")?<details className={styles.details}><summary>Estornar liquidação manual</summary><div className={styles.detailBody}><ReverseSettlementForm transactionId={tx.id}/></div></details>:null}</div>)}</div>}</article>
  </section>;
}
function Metric({label,value,warning=false,tone}:{label:string;value:string;warning?:boolean;tone?:"good"|"bad"}){return <article className={`card ${styles.metric}`}><span className={styles.metricLabel}>{label}</span><strong className={`${styles.metricValue} ${tone==="good"?styles.good:tone==="bad"?styles.bad:warning?styles.warning:""}`}>{value}</strong></article>}
function Rows({rows}:{rows:Array<[string,number|string]>}){return <div className={styles.rows}>{rows.map(([label,value])=><div key={label} className={styles.row}><span className="muted">{label}</span><strong>{brl(value)}</strong></div>)}</div>}
