import fs from"node:fs";import path from"node:path";import{describe,expect,it}from"vitest";const r=(f:string)=>fs.readFileSync(path.join(process.cwd(),f),"utf8");
const layout=r("src/app/platform/layout.tsx"),support=r("src/server/platform/platform-support-action-service.ts"),accounts=r("src/server/platform/platform-account-support-service.ts"),billing=r("src/server/platform/platform-commercial-billing-service.ts"),incidents=r("src/server/platform/platform-incident-service.ts"),mode=r("src/server/platform/platform-support-mode-service.ts"),integrity=r("src/server/platform/platform-integrity-service.ts"),alerts=r("src/server/platform/platform-alert-service.ts"),doc=r("docs/PLATFORM_SUPPORT_HOMOLOGATION_348.md");
describe("final platform support homologation [348]",()=>{
it("keeps every final support surface reachable from the owner platform",()=>{for(const route of["/platform/operacao","/platform/integracoes","/platform/assinaturas","/platform/incidentes","/platform/alertas","/platform/suporte","/platform/suporte/modo","/platform/integridade"])expect(layout).toContain(route);});
it("keeps support mutations explicit audited and tenant scoped",()=>{expect(support).toContain("idempotency");expect(support).toContain("audit");expect(accounts).toContain('targetRole.key === "owner"');expect(accounts).toContain("resetPasswordForEmail");expect(billing).toContain("PlatformAdminService.applySubscription");});
it("does not create unsafe overrides for finance or order state machines",()=>{const joined=[support,accounts,billing,integrity,alerts].join("\n");expect(joined).not.toMatch(/from\("orders"\)\.update/);expect(joined).not.toMatch(/from\("payments"\)\.update/);expect(joined).not.toContain('payment_status:"paid"');expect(joined).not.toContain('order_status:"completed"');});
it("keeps incident observability sanitized",()=>{expect(incidents).toContain("safeObject");expect(incidents).toContain("secretKey");expect(incidents).not.toContain('select("payload');});
it("keeps support mode temporary read-only and separate from customer auth",()=>{expect(mode).toContain("httpOnly:true");expect(mode).toContain("timingSafeEqual");expect(mode).not.toContain("setSession");expect(mode).not.toContain("refresh_token");});
it("requires deterministic integrity repairs and confirmation",()=>{expect(integrity).toContain("static async dryRun");expect(integrity).toContain('z.literal("APLICAR REPARO")');expect(integrity).not.toContain("SQL");});
it("keeps proactive alerts read-only and deduplicated",()=>{expect(alerts).toContain("new Map<string, Alert>()");expect(alerts).not.toContain(".update(");expect(alerts).not.toContain(".insert(");});
it("refuses to equate CI with external real-world provider homologation",()=>{expect(doc).toContain("Gates externos obrigatórios");expect(doc).toContain("Não fechar #462");expect(doc).toContain("telefone físico");expect(doc).toContain("provider real");});
});
