import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";
import {
  TRACKING_NOT_FOUND_MESSAGE,
  phonesBelongToSameCustomer,
  resolveWhatsAppBotIntent,
  trackingCodeFromInput,
} from "@/server/conversations/bot-menu";

describe("WPP-FOLLOW-02 inbound order follow contract", () => {
  it("recognizes the exact prefilled message generated by WPP-FOLLOW-01", () => {
    const message = "Olá! Quero acompanhar meu pedido #115 pelo WhatsApp.";
    expect(trackingCodeFromInput(message)).toBe(115);
    expect(resolveWhatsAppBotIntent(message, "menu")).toBe("track_code");
  });

  it("recognizes natural explicit tracking messages without depending on punctuation", () => {
    const samples = [
      ["acompanhar pedido #123", 123],
      ["onde está meu pedido 456?", 456],
      ["como está o pedido #789", 789],
    ] as const;

    for (const [message, number] of samples) {
      expect(trackingCodeFromInput(message)).toBe(number);
      expect(resolveWhatsAppBotIntent(message, "menu")).toBe("track_code");
    }
  });

  it("asks for the order number instead of guessing when tracking has no explicit number", () => {
    expect(trackingCodeFromInput("quero acompanhar meu pedido")).toBeNull();
    expect(resolveWhatsAppBotIntent("quero acompanhar meu pedido", "menu")).toBe("track_start");
  });

  it("normalizes Brazilian local/DDI formats while rejecting a genuinely different phone", () => {
    expect(phonesBelongToSameCustomer("(19) 99999-1234", "+55 19 99999-1234")).toBe(true);
    expect(phonesBelongToSameCustomer("5519999991234", "19 99999-1234")).toBe(true);
    expect(phonesBelongToSameCustomer("5519999991234", "5519888881234")).toBe(false);
  });

  it("keeps the negative response generic and free from sensitive order details", () => {
    expect(TRACKING_NOT_FOUND_MESSAGE).toContain("não encontrei esse pedido ligado ao seu número");
    expect(TRACKING_NOT_FOUND_MESSAGE).not.toMatch(/token|endereço|rua|total|R\$|item/i);
  });

  it("keeps the lookup tenant-scoped and phone-authorized", () => {
    const source = readFileSync("src/server/conversations/greeting-service.ts", "utf8");
    expect(source).toContain('.eq("organization_id", result.organization_id)');
    expect(source).toContain('.eq("store_id", result.store_id)');
    expect(source).toContain('.eq("display_number", displayNumber)');
    expect(source).toContain("phonesBelongToSameCustomer(order.customer_phone_snapshot, contact.phone_normalized)");
  });

  it("preserves inbound idempotency and suppresses bot replies during human handoff", () => {
    const greeting = readFileSync("src/server/conversations/greeting-service.ts", "utf8");
    const orchestrator = readFileSync("src/server/conversations/whatsapp-direct-order-orchestrator.ts", "utf8");

    expect(greeting).toContain("if (!result.message_created) return false");
    expect(orchestrator).toContain("if (!result.message_created) return false");
    expect(greeting).toContain('conversation.status !== "bot"');
    expect(orchestrator).toContain('conversation.status !== "bot"');
  });
});
