import Link from "next/link";
import { PurchaseService } from "@/server/purchases/purchase-service";
import { CancelPurchaseForm, CorrectReceiptForm, PurchaseCreateForm, ReceivePurchaseForm, SendPurchaseForm } from "@/features/purchases/purchase-forms";

const statusLabels: Record<string,string> = { draft: "Rascunho", sent: "Enviado", partially_received: "Recebido parcial", received: "Recebido", cancelled: "Cancelado" };
function money(cents: number | string) { return new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" }).format(Number(cents || 0) / 100); }
function date(value: string | null) { return value ? new Date(value).toLocaleString("pt-BR") : "—"; }

export default async function PurchasesPage() {
  const data = await PurchaseService.load();
  const activeSupplierIds = new Set(data.supplierConfigs.filter((row) => row.active).map((row) => row.supplier_id));
  const suppliers = data.suppliers.filter((supplier) => activeSupplierIds.has(supplier.id));
  const open = data.orders.filter((order) => ["draft","sent","partially_received"].includes(order.status));
  const received = data.orders.filter((order) => order.status === "received");

  return <section style={{ display: "grid", gap: 18, maxWidth: 1320 }}>
    <header style={{ display: "flex", justifyContent: "space-between", gap: 16, alignItems: "end", flexWrap: "wrap" }}>
      <div><p className="muted" style={{ margin: 0 }}>Suprimentos por unidade</p><h1 style={{ margin: "3px 0" }}>Compras</h1><p className="muted" style={{ margin: 0, maxWidth: 780 }}>Pedido, recebimento e estoque formam uma única trilha. O recebimento converte a embalagem para a unidade-base e atualiza o ledger/custo médio na mesma transação.</p></div>
      <div style={{ display: "flex", gap: 14 }}><Link href="/fornecedores" style={{ color: "var(--accent)", fontWeight: 850 }}>Fornecedores</Link><Link href="/estoque" style={{ color: "var(--accent)", fontWeight: 850 }}>Estoque →</Link></div>
    </header>

    <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(170px,1fr))", gap: 10 }}><Metric label="Pedidos abertos" value={open.length} /><Metric label="Recebidos" value={received.length} /><Metric label="Sugestões de reposição" value={data.suggestions.length} warning={data.suggestions.length > 0} /><Metric label="Fornecedores ativos" value={suppliers.length} /></div>

    {data.suggestions.length ? <article className="card" style={{ padding: 16, display: "grid", gap: 10 }}><div><h2 style={{ margin: 0, fontSize: 18 }}>Sugestões de reposição</h2><p className="muted" style={{ margin: "4px 0 0", fontSize: 11 }}>São recomendações operacionais. Nenhum pedido é criado sem confirmação humana.</p></div><div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(240px,1fr))", gap: 8 }}>{data.suggestions.map((item) => {
      const supplier = data.suppliers.find((candidate) => candidate.id === item.preferredSupplierId);
      return <div key={item.inventoryItemId} style={{ border: "1px solid var(--border)", borderRadius: 10, padding: 10 }}><strong>{item.name}</strong><div className="muted" style={{ fontSize: 11, marginTop: 3 }}>Saldo {item.current} · mínimo {item.minimum} · falta {item.shortage} {item.baseUnit === "unit" ? "un" : item.baseUnit}</div><div style={{ fontSize: 11, marginTop: 5 }}>{supplier ? `${supplier.name}${item.suggestedPurchaseQuantity !== null ? ` · sugestão ${item.suggestedPurchaseQuantity} ${item.purchaseUnitLabel ?? "emb."}` : ""}` : "Sem fornecedor configurado"}</div></div>;
    })}</div></article> : null}

    {data.canManage ? <article className="card" style={{ padding: 16, display: "grid", gap: 10 }}><div><h2 style={{ margin: 0, fontSize: 18 }}>Novo pedido de compra</h2><p className="muted" style={{ margin: "4px 0 0", fontSize: 11 }}>Preencha quantidade nas linhas desejadas. O total e as conversões são recalculados no servidor.</p></div><PurchaseCreateForm suppliers={suppliers} catalog={data.catalog} /></article> : null}

    <div style={{ display: "grid", gap: 12 }}><h2 style={{ margin: 0, fontSize: 18 }}>Pedidos recentes</h2>{data.orders.length === 0 ? <article className="card" style={{ padding: 18 }}><p className="muted" style={{ margin: 0 }}>Nenhum pedido de compra nesta unidade.</p></article> : data.orders.map((order) => <article key={order.id} className="card" style={{ padding: 16, display: "grid", gap: 12 }}>
      <div style={{ display: "flex", justifyContent: "space-between", gap: 12, flexWrap: "wrap" }}><div><strong style={{ fontSize: 19 }}>Compra #{order.display_number}</strong><div className="muted" style={{ fontSize: 11, marginTop: 3 }}>{order.supplier?.name ?? "Fornecedor"} · criada {date(order.created_at)}</div></div><div style={{ textAlign: "right" }}><strong style={{ color: order.status === "cancelled" ? "#f97066" : order.status === "received" ? "#22c55e" : "var(--accent)" }}>{statusLabels[order.status] ?? order.status}</strong><div className="muted" style={{ fontSize: 11 }}>{money(order.subtotal_cents)} · previsão {date(order.expected_at)}</div></div></div>
      <div style={{ display: "grid", gap: 5 }}>{order.items.map((item) => <div key={item.id} style={{ display: "flex", justifyContent: "space-between", gap: 10, borderTop: "1px solid var(--border)", paddingTop: 7, fontSize: 12 }}><span><strong>{item.inventory_name_snapshot}</strong><span className="muted"> · {item.purchase_unit_label_snapshot} = {String(item.base_units_per_purchase_unit_snapshot)} {item.base_unit_snapshot}</span></span><span>{String(item.received_purchase_quantity)}/{String(item.ordered_purchase_quantity)} · {money(item.unit_cost_cents)}/emb. · {money(item.line_total_cents)}</span></div>)}</div>
      {data.canManage && order.status === "draft" ? <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(220px,1fr))", gap: 8 }}><SendPurchaseForm orderId={order.id} /><CancelPurchaseForm orderId={order.id} /></div> : null}
      {data.canManage && order.status === "sent" && order.receipts.length === 0 ? <details><summary style={{ cursor: "pointer", fontWeight: 800, color: "#f97066" }}>Cancelar antes do recebimento</summary><div style={{ marginTop: 8 }}><CancelPurchaseForm orderId={order.id} /></div></details> : null}
      {data.canReceive && ["sent","partially_received"].includes(order.status) ? <details open={order.status === "partially_received"}><summary style={{ cursor: "pointer", fontWeight: 850 }}>Registrar recebimento</summary><div style={{ marginTop: 9 }}><ReceivePurchaseForm orderId={order.id} items={order.items} /></div></details> : null}
      {order.receipts.length ? <details><summary style={{ cursor: "pointer", fontWeight: 800 }}>Histórico de recebimentos ({order.receipts.length})</summary><div style={{ marginTop: 9, display: "grid", gap: 8 }}>{order.receipts.map((receipt) => <div key={receipt.id} style={{ borderTop: "1px solid var(--border)", paddingTop: 8 }}><div style={{ display: "flex", justifyContent: "space-between", gap: 10, flexWrap: "wrap", fontSize: 12 }}><strong>{receipt.receipt_kind === "receipt" ? "Recebimento" : "Correção"} · {date(receipt.created_at)}</strong><span className="muted">{receipt.reference || receipt.notes || "Sem referência"}</span></div>{receipt.items.map((ri) => { const item = order.items.find((candidate) => candidate.id === ri.purchase_order_item_id); return <div key={ri.id} className="muted" style={{ fontSize: 11, marginTop: 4 }}>{item?.inventory_name_snapshot ?? "Item"}: {Number(ri.purchase_quantity_delta) > 0 ? "+" : ""}{String(ri.purchase_quantity_delta)} {item?.purchase_unit_label_snapshot ?? "emb."} · {money(ri.unit_cost_cents)}</div>; })}{data.canReceive && receipt.receipt_kind === "receipt" && ["partially_received","received"].includes(order.status) ? <details style={{ marginTop: 7 }}><summary style={{ cursor: "pointer", fontSize: 12, fontWeight: 800 }}>Corrigir este recebimento</summary><div style={{ marginTop: 7 }}><CorrectReceiptForm orderId={order.id} receiptId={receipt.id} items={order.items} /></div></details> : null}</div>)}</div></details> : null}
      {order.history.length ? <div className="muted" style={{ fontSize: 10 }}>Fluxo: {order.history.map((entry) => statusLabels[entry.to_status] ?? entry.to_status).join(" → ")}</div> : null}
    </article>)}</div>
  </section>;
}
function Metric({ label, value, warning = false }: { label: string; value: number; warning?: boolean }) { return <div className="card" style={{ padding: 14 }}><span className="muted" style={{ fontSize: 10 }}>{label.toUpperCase()}</span><strong style={{ display: "block", marginTop: 3, fontSize: 24, color: warning ? "#f59e0b" : undefined }}>{value}</strong></div>; }
