import Link from "next/link";
import { SemanticStatus } from "@/components/ui/status";
import { PurchaseService } from "@/server/purchases/purchase-service";
import { CancelPurchaseForm, CorrectReceiptForm, PurchaseCreateForm, ReceivePurchaseForm, SendPurchaseForm } from "@/features/purchases/purchase-forms";
import styles from "@/features/purchases/procurement.module.css";

const statusLabels: Record<string,string> = { draft: "Rascunho", sent: "Aguardando recebimento", partially_received: "Recebimento parcial", received: "Recebido", cancelled: "Cancelado" };
type StatusPresentation = { tone:"neutral"|"info"|"success"|"warning"|"danger"; icon:string };
const fallbackStatus: StatusPresentation = { tone:"neutral", icon:"○" };
const statusTone: Record<string,StatusPresentation> = { draft:{tone:"neutral",icon:"○"}, sent:{tone:"info",icon:"→"}, partially_received:{tone:"warning",icon:"!"}, received:{tone:"success",icon:"✓"}, cancelled:{tone:"danger",icon:"×"} };
function money(cents: number | string) { return new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" }).format(Number(cents || 0) / 100); }
function date(value: string | null) { return value ? new Date(value).toLocaleString("pt-BR") : "—"; }

export default async function PurchasesPage() {
  const data = await PurchaseService.load();
  const activeSupplierIds = new Set(data.supplierConfigs.filter((row) => row.active).map((row) => row.supplier_id));
  const suppliers = data.suppliers.filter((supplier) => activeSupplierIds.has(supplier.id));
  const open = data.orders.filter((order) => ["draft","sent","partially_received"].includes(order.status));
  const received = data.orders.filter((order) => order.status === "received");
  const partial = data.orders.filter((order) => order.status === "partially_received");

  return <section className={styles.page}>
    <header className={styles.header}><div className={styles.headerCopy}><p className="muted">Suprimentos por unidade</p><h1>Compras</h1><p className="muted">A necessidade vira pedido, o pedido é enviado ao fornecedor e cada recebimento movimenta o estoque pela rotina autoritativa existente.</p></div><div className={styles.links}><Link href="/fornecedores" className={styles.link}>Fornecedores</Link><Link href="/estoque" className={styles.link}>Estoque →</Link></div></header>
    <div className={styles.flow} aria-label="Fluxo de compras"><FlowStep title="1. Necessidade" text="Estoque mínimo e reposição"/><FlowStep title="2. Pedido" text="Quantidade e custo"/><FlowStep title="3. Fornecedor" text="Condições da unidade"/><FlowStep title="4. Recebimento" text="Total ou parcial"/><FlowStep title="5. Estoque" text="Ledger atualizado"/></div>
    <div className={styles.metrics}><Metric label="Pedidos abertos" value={open.length}/><Metric label="Recebimentos parciais" value={partial.length} warning={partial.length>0}/><Metric label="Sugestões de reposição" value={data.suggestions.length} warning={data.suggestions.length>0}/><Metric label="Recebidos" value={received.length}/></div>
    {data.suggestions.length ? <article className={`card ${styles.card}`}><div><h2>Sugestões de reposição</h2><p className="muted">Nenhum pedido é criado automaticamente. A sugestão serve para iniciar uma decisão de compra.</p></div><div className={styles.suggestions}>{data.suggestions.map((item)=>{const supplier=data.suppliers.find((candidate)=>candidate.id===item.preferredSupplierId);return <div key={item.inventoryItemId} className={styles.suggestion}><strong>{item.name}</strong><span className={styles.suggestionMeta}>Saldo {item.current} · mínimo {item.minimum} · falta {item.shortage} {item.baseUnit === "unit" ? "un" : item.baseUnit}</span><span>{supplier ? `${supplier.name}${item.suggestedPurchaseQuantity!==null ? ` · sugestão ${item.suggestedPurchaseQuantity} ${item.purchaseUnitLabel??"emb."}`:""}`:"Sem fornecedor configurado"}</span></div>;})}</div></article>:null}
    {data.canManage ? <article className={`card ${styles.card}`}><div><h2>Novo pedido de compra</h2><p className="muted">O total e as conversões de embalagem são recalculados no servidor.</p></div><PurchaseCreateForm suppliers={suppliers} catalog={data.catalog}/></article>:null}
    <div className={styles.orders}><div className={styles.sectionHeader}><h2 className={styles.sectionTitle}>Pedidos e recebimentos</h2><span className="muted">{open.length} em andamento</span></div>{data.orders.length===0 ? <article className={`card ${styles.card}`}><p className="muted">Nenhum pedido de compra nesta unidade.</p></article> : data.orders.map((order)=>{const status:StatusPresentation=statusTone[order.status]??fallbackStatus;return <article key={order.id} className={`card ${styles.order}`}>
      <div className={styles.top}><div className={styles.identity}><strong>Compra #{order.display_number}</strong><span className={styles.meta}>{order.supplier?.name??"Fornecedor"} · criada {date(order.created_at)}</span><SemanticStatus tone={status.tone} icon={status.icon} label={statusLabels[order.status]??order.status}/></div><div className={styles.side}><strong>{money(order.subtotal_cents)}</strong><span className={styles.meta}>previsão {date(order.expected_at)}</span></div></div>
      <div className={styles.items}>{order.items.map((item)=>{const ordered=Number(item.ordered_purchase_quantity);const receivedQty=Number(item.received_purchase_quantity);const hasDifference=receivedQty>0 && receivedQty<ordered;return <div key={item.id} className={styles.item}><span><strong>{item.inventory_name_snapshot}</strong><span className="muted"> · {item.purchase_unit_label_snapshot} = {String(item.base_units_per_purchase_unit_snapshot)} {item.base_unit_snapshot}</span>{hasDifference ? <strong className={styles.warning}> · parcial</strong>:null}</span><span>{String(item.received_purchase_quantity)}/{String(item.ordered_purchase_quantity)} · {money(item.unit_cost_cents)}/emb. · {money(item.line_total_cents)}</span></div>;})}</div>
      <div className={styles.actions}>{data.canManage && order.status==="draft" ? <><div><SendPurchaseForm orderId={order.id}/></div><div><CancelPurchaseForm orderId={order.id}/></div></>:null}{data.canManage && order.status==="sent" && order.receipts.length===0 ? <details><summary>Cancelar antes do recebimento</summary><div className={styles.actionBody}><CancelPurchaseForm orderId={order.id}/></div></details>:null}{data.canReceive && ["sent","partially_received"].includes(order.status) ? <details open={order.status==="partially_received"}><summary>Registrar recebimento</summary><div className={styles.actionBody}><ReceivePurchaseForm orderId={order.id} items={order.items}/></div></details>:null}</div>
      {order.receipts.length ? <details><summary>Histórico de recebimentos ({order.receipts.length})</summary><div className={styles.actionBody}>{order.receipts.map((receipt)=><div key={receipt.id} className={styles.card}><strong>{receipt.receipt_kind==="receipt"?"Recebimento":"Correção"} · {date(receipt.created_at)}</strong><span className={styles.meta}>{receipt.reference||receipt.notes||"Sem referência"}</span>{receipt.items.map((ri)=>{const item=order.items.find((candidate)=>candidate.id===ri.purchase_order_item_id);return <div key={ri.id} className={styles.meta}>{item?.inventory_name_snapshot??"Item"}: {Number(ri.purchase_quantity_delta)>0?"+":""}{String(ri.purchase_quantity_delta)} {item?.purchase_unit_label_snapshot??"emb."} · {money(ri.unit_cost_cents)}</div>;})}{data.canReceive && receipt.receipt_kind==="receipt" && ["partially_received","received"].includes(order.status) ? <details><summary>Corrigir este recebimento</summary><div className={styles.actionBody}><CorrectReceiptForm orderId={order.id} receiptId={receipt.id} items={order.items}/></div></details>:null}</div>)}</div></details>:null}
      {order.history.length ? <span className={styles.meta}>Fluxo: {order.history.map((entry)=>statusLabels[entry.to_status]??entry.to_status).join(" → ")}</span>:null}
    </article>;})}</div>
  </section>;
}
function FlowStep({title,text}:{title:string;text:string}){return <div className={styles.flowStep}><strong>{title}</strong><span>{text}</span></div>}
function Metric({label,value,warning=false}:{label:string;value:number;warning?:boolean}){return <div className={`card ${styles.metric}`}><span className={styles.metricLabel}>{label}</span><strong className={`${styles.metricValue} ${warning?styles.warning:""}`}>{value}</strong></div>}
