import "server-only";
import { z } from "zod";
import { createAdminClient } from "@/lib/supabase/admin";
import { PlatformAdminService,PlatformAuthorizationError } from "@/server/platform/platform-admin-service";

const repairSchema=z.object({kind:z.enum(["create_menu_shell","retry_print_job","retry_fiscal_job","retry_webhook"]),organizationId:z.string().uuid(),storeId:z.string().uuid().nullable(),entityId:z.string().uuid(),reason:z.string().trim().min(5).max(500),protocol:z.string().trim().min(3).max(120),idempotencyKey:z.string().trim().min(8).max(160),confirmation:z.literal("APLICAR REPARO")});
async function elevated(){const access=await PlatformAdminService.access();if(access.role!=="super_admin")throw new PlatformAuthorizationError();return access;}
async function claim(org:string,key:string){const admin=createAdminClient();const{error}=await admin.from("idempotency_keys").insert({organization_id:org,store_id:null,scope:"platform.integrity.repair",idempotency_key:key,request_fingerprint:key,status:"processing",expires_at:new Date(Date.now()+86400000).toISOString()});if(!error)return true;if(error.code==="23505")return false;throw error;}
export class PlatformIntegrityService{
 static async load(){await PlatformAdminService.access();const admin=createAdminClient();const[orgs,stores,menus,members,roles,printJobs,fiscalJobs,webhooks]=await Promise.all([admin.from("organizations").select("id,name"),admin.from("stores").select("id,organization_id,name,status").order("name"),admin.from("store_menu_settings").select("organization_id,store_id"),admin.from("organization_members").select("id,organization_id,user_id,status").eq("status","active"),admin.from("user_store_roles").select("organization_id,store_id,user_id,role_id"),admin.from("print_jobs").select("id,organization_id,store_id,status,attempts,max_attempts,last_error,updated_at").eq("status","failed").limit(200),admin.from("fiscal_jobs").select("id,organization_id,store_id,status,attempts,max_attempts,last_error,updated_at").eq("status","dead").limit(200),admin.from("integration_webhook_deliveries").select("id,organization_id,store_id,status,attempts,max_attempts,last_error,updated_at").eq("status","dead").limit(200)]);for(const r of[orgs,stores,menus,members,roles,printJobs,fiscalJobs,webhooks])if(r.error)throw r.error;const orgName=new Map((orgs.data??[]).map(o=>[o.id,o.name]));const menuKeys=new Set((menus.data??[]).map(m=>`${m.organization_id}:${m.store_id}`));const roleUsers=new Set((roles.data??[]).map(r=>`${r.organization_id}:${r.user_id}`));const checks:Array<Record<string,unknown>>=[];
 for(const store of stores.data??[])if(store.status==="active"&&!menuKeys.has(`${store.organization_id}:${store.id}`))checks.push({kind:"create_menu_shell",tone:"danger",organizationId:store.organization_id,organizationName:orgName.get(store.organization_id),storeId:store.id,storeName:store.name,entityId:store.id,title:"Unidade ativa sem configuração-base de cardápio",detail:"Reparo disponível: recriar somente a estrutura em estado seguro e desabilitado.",repairable:true});
 for(const member of members.data??[])if(!roleUsers.has(`${member.organization_id}:${member.user_id}`))checks.push({kind:"membership_without_store_role",tone:"warn",organizationId:member.organization_id,organizationName:orgName.get(member.organization_id),storeId:null,storeName:null,entityId:member.id,title:"Membro ativo sem acesso a unidade",detail:"Exige decisão de permissão; a Central de Integridade não inventa função nem unidade.",repairable:false});
 for(const job of printJobs.data??[])checks.push({kind:"retry_print_job",tone:"warn",organizationId:job.organization_id,organizationName:orgName.get(job.organization_id),storeId:job.store_id,storeName:null,entityId:job.id,title:"Job de impressão recuperável",detail:job.attempts<job.max_attempts?"Retry idempotente disponível.":"Limite de tentativas atingido; exige diagnóstico antes de novo envio.",repairable:job.attempts<job.max_attempts});
 for(const job of fiscalJobs.data??[])checks.push({kind:"retry_fiscal_job",tone:"warn",organizationId:job.organization_id,organizationName:orgName.get(job.organization_id),storeId:job.store_id,storeName:null,entityId:job.id,title:"Job fiscal em dead-letter",detail:job.attempts<job.max_attempts?"Pode voltar à fila sem alterar o documento fiscal.":"Limite de tentativas atingido; não será reiniciado automaticamente.",repairable:job.attempts<job.max_attempts});
 for(const job of webhooks.data??[])checks.push({kind:"retry_webhook",tone:"warn",organizationId:job.organization_id,organizationName:orgName.get(job.organization_id),storeId:job.store_id,storeName:null,entityId:job.id,title:"Webhook externo em dead-letter",detail:job.attempts<job.max_attempts?"Pode voltar à fila mantendo o mesmo evento.":"Limite de tentativas atingido; requer diagnóstico.",repairable:job.attempts<job.max_attempts});
 return{checks,totals:{blocking:checks.filter(c=>c.tone==="danger").length,attention:checks.filter(c=>c.tone==="warn").length,repairable:checks.filter(c=>c.repairable).length},canRepair:(await PlatformAdminService.access()).role==="super_admin"};}
 static async dryRun(input:z.input<typeof repairSchema>){const values=repairSchema.parse(input);await elevated();const admin=createAdminClient();const store=values.storeId?await admin.from("stores").select("id,organization_id,name").eq("id",values.storeId).eq("organization_id",values.organizationId).single():{data:null,error:null};if(values.storeId&&(store.error||!store.data))throw new Error("Unidade fora do tenant.");return{kind:values.kind,organizationId:values.organizationId,storeId:values.storeId,entityId:values.entityId,effect:values.kind==="create_menu_shell"?"Cria configuração-base fechada: cardápio, pedidos, entrega e retirada permanecem desabilitados.":"Recoloca somente o job selecionado na fila, preservando payload, idempotência e fonte autoritativa."};}
 static async repair(input:z.input<typeof repairSchema>){const values=repairSchema.parse(input);const access=await elevated();await this.dryRun(values);if(!await claim(values.organizationId,values.idempotencyKey))return{duplicate:true};const admin=createAdminClient();let before:unknown=null;let after:unknown=null;
 if(values.kind==="create_menu_shell"){const{data:store}=await admin.from("stores").select("id").eq("id",values.entityId).eq("organization_id",values.organizationId).single();if(!store)throw new Error("Unidade inválida.");const existing=await admin.from("store_menu_settings").select("store_id").eq("organization_id",values.organizationId).eq("store_id",values.entityId).maybeSingle();if(existing.data)return{duplicate:true};const{error}=await admin.from("store_menu_settings").insert({organization_id:values.organizationId,store_id:values.entityId,active:false,accepting_orders:false,allow_delivery:false,allow_pickup:false,pause_reason:"Configuração estrutural recriada pelo suporte"});if(error)throw error;after={state:"safe_disabled"};}
 else{const table=values.kind==="retry_print_job"?"print_jobs":values.kind==="retry_fiscal_job"?"fiscal_jobs":"integration_webhook_deliveries";const terminal=values.kind==="retry_print_job"?"failed":"dead";const next="pending";const{data:job,error:readError}=await admin.from(table).select("id,status,attempts,max_attempts").eq("id",values.entityId).eq("organization_id",values.organizationId).eq("status",terminal).single();if(readError||!job||job.attempts>=job.max_attempts)throw new Error("Job não é elegível para retry seguro.");before={status:job.status,attempts:job.attempts};const patch:Record<string,unknown>={status:next,available_at:new Date().toISOString(),updated_at:new Date().toISOString()};if(values.kind==="retry_print_job"){patch.claimed_by_agent_id=null;patch.lease_expires_at=null;patch.processing_at=null;}else{patch.leased_at=null;patch.lease_expires_at=null;patch.leased_by=null;}const{error}=await admin.from(table).update(patch).eq("id",values.entityId).eq("organization_id",values.organizationId).eq("status",terminal);if(error)throw error;after={status:next,attempts:job.attempts};}
 await admin.from("audit_logs").insert({organization_id:values.organizationId,store_id:values.storeId,actor_user_id:access.user.id,action:`platform.integrity.${values.kind}`,entity_type:"integrity_repair",entity_id:values.entityId,before_data:before,after_data:{...(after as object),reason:values.reason,protocol:values.protocol},request_id:values.protocol});await admin.from("idempotency_keys").update({status:"completed",response_code:200,updated_at:new Date().toISOString()}).eq("organization_id",values.organizationId).eq("scope","platform.integrity.repair").eq("idempotency_key",values.idempotencyKey);return{duplicate:false};}
}
