import "server-only";

import { createHmac, timingSafeEqual } from "node:crypto";
import { cookies } from "next/headers";
import { z } from "zod";
import { createAdminClient } from "@/lib/supabase/admin";
import { PlatformAdminService } from "@/server/platform/platform-admin-service";
import { PlatformRestaurant360Service } from "@/server/platform/platform-restaurant-360-service";

const COOKIE = "pedeaqui_support_mode";
const TTL_SECONDS = 30 * 60;
const inputSchema = z.object({ organizationId:z.string().uuid(),storeId:z.string().uuid(),roleId:z.string().uuid().nullable(),reason:z.string().trim().min(5).max(500),protocol:z.string().trim().min(3).max(120) });
type Payload={organizationId:string;storeId:string;roleId:string|null;actorId:string;reason:string;protocol:string;expiresAt:number};
function secret(){ const value=process.env.SUPPORT_MODE_SECRET ?? process.env.SUPABASE_SERVICE_ROLE_KEY; if(!value) throw new Error("Support mode secret unavailable."); return value; }
function sign(encoded:string){ return createHmac("sha256",secret()).update(encoded).digest("base64url"); }
function encode(payload:Payload){ const body=Buffer.from(JSON.stringify(payload)).toString("base64url"); return `${body}.${sign(body)}`; }
function decode(token:string):Payload|null { const [body,signature]=token.split("."); if(!body||!signature)return null; const expected=Buffer.from(sign(body)); const received=Buffer.from(signature); if(expected.length!==received.length||!timingSafeEqual(expected,received))return null; try { const parsed=JSON.parse(Buffer.from(body,"base64url").toString("utf8")) as Payload; return parsed.expiresAt>Date.now()?parsed:null; } catch{return null;} }
async function validateTarget(organizationId:string,storeId:string,roleId:string|null){ const admin=createAdminClient(); const [org,store,role]=await Promise.all([admin.from("organizations").select("id,name").eq("id",organizationId).single(),admin.from("stores").select("id,organization_id,name").eq("id",storeId).eq("organization_id",organizationId).single(),roleId?admin.from("roles").select("id,organization_id,key,name").eq("id",roleId).eq("organization_id",organizationId).single():Promise.resolve({data:null,error:null})]); if(org.error||store.error||!org.data||!store.data)throw new Error("Contexto de suporte inválido."); if(roleId&&(role.error||!role.data))throw new Error("Perfil funcional inválido."); return {organization:org.data,store:store.data,role:role.data}; }
export class PlatformSupportModeService {
 static async start(input:z.input<typeof inputSchema>){ const values=inputSchema.parse(input); const access=await PlatformAdminService.access(); const target=await validateTarget(values.organizationId,values.storeId,values.roleId); const payload:Payload={...values,actorId:access.user.id,expiresAt:Date.now()+TTL_SECONDS*1000}; (await cookies()).set(COOKIE,encode(payload),{httpOnly:true,sameSite:"lax",secure:process.env.NODE_ENV==="production",path:"/platform",maxAge:TTL_SECONDS}); const admin=createAdminClient(); await admin.from("audit_logs").insert({organization_id:values.organizationId,store_id:values.storeId,actor_user_id:access.user.id,action:"platform.support_mode.started",entity_type:"store",entity_id:values.storeId,before_data:null,after_data:{role_id:values.roleId,expires_at:new Date(payload.expiresAt).toISOString(),reason:values.reason,protocol:values.protocol},request_id:values.protocol}); return target; }
 static async current(){ const access=await PlatformAdminService.access(); const raw=(await cookies()).get(COOKIE)?.value; if(!raw)return null; const payload=decode(raw); if(!payload||payload.actorId!==access.user.id){(await cookies()).delete(COOKIE);return null;} const target=await validateTarget(payload.organizationId,payload.storeId,payload.roleId); const snapshot=await PlatformRestaurant360Service.load(payload.organizationId,payload.storeId); const admin=createAdminClient(); const permissions=payload.roleId?await admin.from("role_permissions").select("permission_id,permissions(key,name)").eq("role_id",payload.roleId):{data:[],error:null}; if(permissions.error)throw permissions.error; return {payload,target,snapshot,permissions:permissions.data??[]}; }
 static async end(){ const access=await PlatformAdminService.access(); const store=await cookies(); const raw=store.get(COOKIE)?.value; const payload=raw?decode(raw):null; store.delete(COOKIE); if(payload&&payload.actorId===access.user.id){const admin=createAdminClient(); await admin.from("audit_logs").insert({organization_id:payload.organizationId,store_id:payload.storeId,actor_user_id:access.user.id,action:"platform.support_mode.ended",entity_type:"store",entity_id:payload.storeId,before_data:null,after_data:{reason:payload.reason,protocol:payload.protocol},request_id:payload.protocol});} }
 static async options(){ await PlatformAdminService.access(); const admin=createAdminClient(); const [orgs,stores,roles]=await Promise.all([admin.from("organizations").select("id,name").order("name"),admin.from("stores").select("id,organization_id,name").order("name"),admin.from("roles").select("id,organization_id,key,name").order("name")]); for(const r of [orgs,stores,roles])if(r.error)throw r.error; return {organizations:orgs.data??[],stores:stores.data??[],roles:roles.data??[]}; }
}
