import "server-only";
import {createHmac,timingSafeEqual}from"node:crypto";import{cookies}from"next/headers";import{z}from"zod";import{createAdminClient}from"@/lib/supabase/admin";import{PlatformAdminService}from"@/server/platform/platform-admin-service";import{PlatformRestaurant360Service}from"@/server/platform/platform-restaurant-360-service";
const COOKIE="pedeaqui_support_mode",TTL_SECONDS=30*60;const inputSchema=z.object({organizationId:z.string().uuid(),storeId:z.string().uuid(),roleId:z.string().uuid().nullable(),reason:z.string().trim().min(5).max(500),protocol:z.string().trim().min(3).max(120)});type Payload={organizationId:string;storeId:string;roleId:string|null;actorId:string;reason:string;protocol:string;expiresAt:number};
function secret(){const v=process.env.SUPPORT_MODE_SECRET??process.env.SUPABASE_SERVICE_ROLE_KEY;if(!v)throw new Error("Support mode secret unavailable.");return v}function sign(v:string){return createHmac("sha256",secret()).update(v).digest("base64url")}function encode(p:Payload){const b=Buffer.from(JSON.stringify(p)).toString("base64url");return`${b}.${sign(b)}`}function decode(t:string):Payload|null{const[b,s]=t.split(".");if(!b||!s)return null;const e=Buffer.from(sign(b)),r=Buffer.from(s);if(e.length!==r.length||!timingSafeEqual(e,r))return null;try{const p=JSON.parse(Buffer.from(b,"base64url").toString("utf8"))as Payload;return p.expiresAt>Date.now()?p:null}catch{return null}}
async function target(orgId:string,storeId:string,roleId:string|null){const a=createAdminClient();const[o,s,r]=await Promise.all([a.from("organizations").select("id,name").eq("id",orgId).single(),a.from("stores").select("id,organization_id,name").eq("id",storeId).eq("organization_id",orgId).single(),roleId?a.from("roles").select("id,organization_id,key,name").eq("id",roleId).eq("organization_id",orgId).single():Promise.resolve({data:null,error:null})]);if(o.error||s.error||!o.data||!s.data)throw new Error("Contexto de suporte inválido.");if(roleId&&(r.error||!r.data))throw new Error("Perfil funcional inválido.");return{organization:o.data,store:s.data,role:r.data}}
export class PlatformSupportModeService{
static async start(i:z.input<typeof inputSchema>){const v=inputSchema.parse(i),access=await PlatformAdminService.access(),t=await target(v.organizationId,v.storeId,v.roleId),p:Payload={...v,actorId:access.user.id,expiresAt:Date.now()+TTL_SECONDS*1000};(await cookies()).set(COOKIE,encode(p),{httpOnly:true,sameSite:"lax",secure:process.env.NODE_ENV==="production",path:"/platform",maxAge:TTL_SECONDS});await createAdminClient().from("audit_logs").insert({organization_id:v.organizationId,store_id:v.storeId,actor_user_id:access.user.id,action:"platform.support_mode.started",entity_type:"store",entity_id:v.storeId,before_data:null,after_data:{role_id:v.roleId,expires_at:new Date(p.expiresAt).toISOString(),reason:v.reason,protocol:v.protocol},request_id:v.protocol});return t}
static async current(){const access=await PlatformAdminService.access(),jar=await cookies(),raw=jar.get(COOKIE)?.value;if(!raw)return null;const p=decode(raw);if(!p||p.actorId!==access.user.id){jar.delete(COOKIE);return null}const t=await target(p.organizationId,p.storeId,p.roleId),snapshot=await PlatformRestaurant360Service.load(p.organizationId,p.storeId),a=createAdminClient();let permissions:Array<{key:string;description:string|null}>=[];if(p.roleId){const links=await a.from("role_permissions").select("permission_id").eq("role_id",p.roleId);if(links.error)throw links.error;const ids=(links.data??[]).map(x=>x.permission_id);if(ids.length){const rows=await a.from("permissions").select("key,description").in("id",ids).order("key");if(rows.error)throw rows.error;permissions=rows.data??[]}}return{payload:p,target:t,snapshot,permissions}}
static async end(){const access=await PlatformAdminService.access(),jar=await cookies(),raw=jar.get(COOKIE)?.value,p=raw?decode(raw):null;jar.delete(COOKIE);if(p&&p.actorId===access.user.id)await createAdminClient().from("audit_logs").insert({organization_id:p.organizationId,store_id:p.storeId,actor_user_id:access.user.id,action:"platform.support_mode.ended",entity_type:"store",entity_id:p.storeId,before_data:null,after_data:{reason:p.reason,protocol:p.protocol},request_id:p.protocol})}
static async options(){await PlatformAdminService.access();const a=createAdminClient(),[o,s,r]=await Promise.all([a.from("organizations").select("id,name").order("name"),a.from("stores").select("id,organization_id,name").order("name"),a.from("roles").select("id,organization_id,key,name").order("name")]);for(const x of[o,s,r])if(x.error)throw x.error;return{organizations:o.data??[],stores:s.data??[],roles:r.data??[]}}
}
