import { SemanticStatus } from "@/components/ui/status";
import { FiscalReadService } from "@/server/fiscal/fiscal-read-service";
import { CancelFiscalDocumentForm,CreateFiscalDraftForm,FiscalIntegrationForm,FiscalProfileForm,ProductFiscalProfileForm,QueueFiscalDocumentForm } from "@/features/fiscal/fiscal-forms";
import styles from "./fiscal-panel.module.css";

const statusLabel:Record<string,string>={draft:"Rascunho",queued:"Na fila",processing:"Processando",authorized:"Autorizado",rejected:"Rejeitado",cancelled:"Cancelado",contingency:"Contingência"};
const statusPresentation:Record<string,{tone:"neutral"|"info"|"success"|"warning"|"danger";icon:string}>={draft:{tone:"neutral",icon:"○"},queued:{tone:"info",icon:"→"},processing:{tone:"info",icon:"…"},authorized:{tone:"success",icon:"✓"},rejected:{tone:"danger",icon:"×"},cancelled:{tone:"neutral",icon:"○"},contingency:{tone:"warning",icon:"!"}};
const fallback={tone:"neutral" as const,icon:"○"};
function brl(cents:number|string){return new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(Number(cents||0)/100)}
function when(value:string|null|undefined){return value?new Date(value).toLocaleString("pt-BR"):"—"}

export default async function FiscalPage(){
  const data=await FiscalReadService.load();
  const jobsByDocument=new Map(data.jobs.map((job)=>[job.fiscal_document_id,job]));
  const pending=data.documents.filter((doc)=>["draft","queued","processing"].includes(doc.status));
  const attention=data.documents.filter((doc)=>["rejected","contingency"].includes(doc.status));
  const completed=data.documents.filter((doc)=>["authorized","cancelled"].includes(doc.status));
  return <section className={styles.page}>
    <header className={styles.header}><p className="muted">Documentos fiscais · operação diária</p><h1>Fiscal e integrações</h1><p className="muted">Pedidos continuam sendo a fonte comercial. Aqui a equipe acompanha o que precisa emitir, o que exige atenção e o que já foi concluído.</p></header>
    <div className={styles.metrics}><Metric label="Pendentes" value={pending.length}/><Metric label="Com atenção" value={attention.length} tone={attention.length?"danger":undefined}/><Metric label="Concluídos" value={completed.length}/><Metric label="Pedidos elegíveis" value={data.eligibleOrders.length} tone={data.eligibleOrders.length?"warning":undefined}/></div>
    {data.canIssue?<article className={`card ${styles.card}`}><div><h2>Pedidos elegíveis</h2><p className="muted">Criar o rascunho congela os dados comerciais e fiscais; emissão só segue quando os itens têm classificação válida.</p></div>{data.eligibleOrders.length===0?<p className="muted">Nenhum pedido recente aguardando documento.</p>:<div className={styles.eligible}>{data.eligibleOrders.map((order)=><div key={order.id} className={styles.eligibleItem}><div><strong>Pedido #{order.display_number}</strong><div className={styles.meta}>{order.customer_name_snapshot} · {brl(order.total_cents)} · {order.order_status}</div></div><CreateFiscalDraftForm orderId={order.id} model={data.profile?.default_document_model??"65"}/></div>)}</div>}</article>:null}
    <div className={styles.queues}><DocumentQueue title="Pendentes" documents={pending} empty="Nenhum documento pendente." data={data} jobsByDocument={jobsByDocument}/><DocumentQueue title="Exigem atenção" documents={attention} empty="Nenhuma rejeição ou contingência." data={data} jobsByDocument={jobsByDocument}/><DocumentQueue title="Concluídos" documents={completed} empty="Nenhum documento concluído." data={data} jobsByDocument={jobsByDocument}/></div>
    {(data.canManage||data.canManageIntegrations)?<details className={styles.details}><summary>Configurações fiscais e classificação de produtos</summary><div className={styles.detailsBody}><div className={styles.configGrid}><article className={`card ${styles.card}`}><h2>Perfil da unidade</h2>{data.profile?<><strong>{data.profile.issuer_tax_id}</strong><span className={styles.meta}>{data.profile.default_document_model==="65"?"NFC-e":"NF-e"} · {data.profile.environment} · {data.profile.emission_policy}</span></>:<p className="muted">Ainda não configurado.</p>}{data.canManage?<details><summary>Editar perfil</summary><div><FiscalProfileForm integrations={data.integrations} current={data.profile}/></div></details>:null}</article><article className={`card ${styles.card}`}><h2>Provider</h2>{data.integrations.length?data.integrations.map((integration)=><div key={integration.id}><strong>{integration.name}</strong><div className={styles.meta}>{integration.provider_key} · {integration.environment} · secret {integration.secret_ref?"referenciado":"ausente"}</div></div>):<p className="muted">Nenhuma integração ativa.</p>}{data.canManageIntegrations?<details><summary>Editar integração</summary><div><FiscalIntegrationForm current={data.integrations[0]??null}/></div></details>:null}</article></div>{data.canManage?<article className={`card ${styles.card}`}><div><h2>Classificação dos produtos</h2><p className="muted">Cada alteração cria nova versão; documentos já enfileirados mantêm o snapshot anterior.</p></div><ProductFiscalProfileForm products={data.products}/><div className={styles.products}>{data.products.slice(0,80).map((product)=><div key={product.id} className={styles.product}><strong>{product.name}</strong><div className={styles.meta}>{product.fiscalProfile?`v${product.fiscalProfile.version} · NCM ${product.fiscalProfile.ncm||"—"} · CFOP ${product.fiscalProfile.default_cfop||"—"}`:"Sem classificação"}</div></div>)}</div></article>:null}</div></details>:null}
  </section>;
}
function Metric({label,value,tone}:{label:string;value:number;tone?:"warning"|"danger"}){return <article className={`card ${styles.metric}`}><span className={styles.metricLabel}>{label}</span><strong className={`${styles.metricValue} ${tone?styles[tone]:""}`}>{value}</strong></article>}
type FiscalData=Awaited<ReturnType<typeof FiscalReadService.load>>;type FiscalDocument=FiscalData["documents"][number];type FiscalJob=FiscalData["jobs"][number];
function DocumentQueue({title,documents,empty,data,jobsByDocument}:{title:string;documents:FiscalDocument[];empty:string;data:FiscalData;jobsByDocument:Map<string,FiscalJob>}){return <section className={styles.queue}><div className={styles.queueHeader}><h2>{title}</h2><span className="muted">{documents.length}</span></div>{documents.length===0?<article className={styles.document}><span className="muted">{empty}</span></article>:documents.map((doc)=>{const job=jobsByDocument.get(doc.id);const present=statusPresentation[doc.status]??fallback;return <article key={doc.id} className={styles.document}><div className={styles.documentTop}><div><strong>{doc.model==="65"?"NFC-e":"NF-e"}</strong><div className={styles.meta}>Criado {when(doc.created_at)} · {doc.environment}{doc.access_key?` · chave ${doc.access_key}`:""}</div></div><SemanticStatus tone={present.tone} icon={present.icon} label={statusLabel[doc.status]??doc.status}/></div>{doc.rejection_message?<div className={styles.error}>{doc.rejection_code?`${doc.rejection_code} · `:""}{doc.rejection_message}</div>:null}{job?<div className={styles.meta}>Job {job.job_type}: {job.status} · tentativas {job.attempts}/{job.max_attempts}{job.last_error?` · ${job.last_error}`:""}</div>:null}{data.canIssue&&(doc.status==="draft"||doc.status==="rejected")?<QueueFiscalDocumentForm fiscalDocumentId={doc.id}/>:null}{data.canCancel&&doc.status==="authorized"?<details><summary>Cancelar documento</summary><CancelFiscalDocumentForm fiscalDocumentId={doc.id}/></details>:null}</article>})}</section>}
