import { FiscalReadService } from "@/server/fiscal/fiscal-read-service";
import { CancelFiscalDocumentForm,CreateFiscalDraftForm,FiscalIntegrationForm,FiscalProfileForm,ProductFiscalProfileForm,QueueFiscalDocumentForm } from "@/features/fiscal/fiscal-forms";

const statusLabel:Record<string,string>={ draft:"Rascunho",queued:"Na fila",processing:"Processando",authorized:"Autorizado",rejected:"Rejeitado",cancelled:"Cancelado",contingency:"Contingência" };
const statusColor:Record<string,string>={ authorized:"#22c55e",rejected:"#f97066",cancelled:"#f97066",contingency:"#f59e0b",processing:"#60a5fa",queued:"#a78bfa" };
function brl(cents:number|string){ return new Intl.NumberFormat("pt-BR",{ style:"currency",currency:"BRL" }).format(Number(cents||0)/100); }
function when(value:string|null|undefined){ return value?new Date(value).toLocaleString("pt-BR"):"—"; }

export default async function FiscalPage(){
  const data=await FiscalReadService.load();
  const jobsByDocument=new Map(data.jobs.map((job)=>[job.fiscal_document_id,job]));
  return <section style={{ display:"grid",gap:18,maxWidth:1360 }}>
    <header><p className="muted" style={{ margin:0 }}>Documentos fiscais desacoplados do pedido</p><h1 style={{ margin:"3px 0" }}>Fiscal e integrações</h1><p className="muted" style={{ margin:0,maxWidth:900 }}>Pedidos continuam sendo a fonte comercial. O módulo fiscal cria snapshots, fila emissão/cancelamento e histórico próprio; indisponibilidade do provider não reescreve o pedido.</p></header>

    <div style={{ display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(280px,1fr))",gap:12,alignItems:"start" }}>
      <article className="card" style={{ padding:16,display:"grid",gap:9 }}><h2 style={{ margin:0,fontSize:18 }}>Perfil da unidade</h2>{data.profile?<><strong>{data.profile.issuer_tax_id}</strong><span className="muted" style={{ fontSize:11 }}>{data.profile.default_document_model==="65"?"NFC-e":"NF-e"} · {data.profile.environment} · {data.profile.emission_policy}</span></>:<p className="muted" style={{ margin:0 }}>Ainda não configurado.</p>}{data.canManage?<details open={!data.profile}><summary style={{ cursor:"pointer",fontWeight:850 }}>Configurar perfil</summary><div style={{ marginTop:9 }}><FiscalProfileForm integrations={data.integrations} current={data.profile}/></div></details>:null}</article>
      <article className="card" style={{ padding:16,display:"grid",gap:9 }}><h2 style={{ margin:0,fontSize:18 }}>Provider fiscal</h2>{data.integrations.length?data.integrations.map((integration)=><div key={integration.id}><strong>{integration.name}</strong><div className="muted" style={{ fontSize:11 }}>{integration.provider_key} · {integration.environment}</div><div className="muted" style={{ fontSize:10 }}>Secret: {integration.secret_ref?"referenciado":"não configurado"} · webhook: {integration.webhook_secret_ref?"referenciado":"não configurado"}</div></div>):<p className="muted" style={{ margin:0 }}>Nenhuma integração fiscal ativa.</p>}{data.canManageIntegrations?<details open={data.integrations.length===0}><summary style={{ cursor:"pointer",fontWeight:850 }}>Configurar integração</summary><div style={{ marginTop:9 }}><FiscalIntegrationForm current={data.integrations[0]??null}/></div></details>:null}</article>
    </div>

    {data.canManage?<article className="card" style={{ padding:16,display:"grid",gap:10 }}><div><h2 style={{ margin:0,fontSize:18 }}>Classificação fiscal dos produtos</h2><p className="muted" style={{ margin:"4px 0 0",fontSize:11 }}>Cada alteração cria uma nova versão. Documentos já enfileirados mantêm o snapshot anterior.</p></div><ProductFiscalProfileForm products={data.products}/><div style={{ display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(220px,1fr))",gap:7 }}>{data.products.slice(0,80).map((product)=><div key={product.id} style={{ border:"1px solid var(--border)",borderRadius:10,padding:10 }}><strong>{product.name}</strong><div className="muted" style={{ fontSize:10 }}>{product.fiscalProfile?`v${product.fiscalProfile.version} · NCM ${product.fiscalProfile.ncm||"—"} · CFOP ${product.fiscalProfile.default_cfop||"—"}`:"Sem classificação fiscal"}</div></div>)}</div></article>:null}

    {data.canIssue?<article className="card" style={{ padding:16,display:"grid",gap:10 }}><div><h2 style={{ margin:0,fontSize:18 }}>Pedidos elegíveis</h2><p className="muted" style={{ margin:"4px 0 0",fontSize:11 }}>Criar o rascunho congela dados comerciais e fiscais em snapshot. A emissão só entra na fila quando todos os itens possuem classificação fiscal.</p></div>{data.eligibleOrders.length===0?<p className="muted" style={{ margin:0 }}>Nenhum pedido recente aguardando documento fiscal.</p>:<div style={{ display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(250px,1fr))",gap:8 }}>{data.eligibleOrders.map((order)=><div key={order.id} style={{ border:"1px solid var(--border)",borderRadius:10,padding:11,display:"grid",gap:7 }}><div><strong>Pedido #{order.display_number}</strong><div className="muted" style={{ fontSize:10 }}>{order.customer_name_snapshot} · {brl(order.total_cents)} · {order.order_status}</div></div><CreateFiscalDraftForm orderId={order.id} model={data.profile?.default_document_model??"65"}/></div>)}</div>}</article>:null}

    <article className="card" style={{ padding:16,display:"grid",gap:10 }}><div><h2 style={{ margin:0,fontSize:18 }}>Documentos fiscais</h2><p className="muted" style={{ margin:"4px 0 0",fontSize:11 }}>State Machine independente: draft → queued → processing → authorized/rejected/contingency; autorizado pode solicitar cancelamento.</p></div>{data.documents.length===0?<p className="muted" style={{ margin:0 }}>Nenhum documento fiscal criado.</p>:data.documents.map((doc)=>{ const job=jobsByDocument.get(doc.id); return <div key={doc.id} style={{ borderTop:"1px solid var(--border)",paddingTop:10,display:"grid",gap:7 }}><div style={{ display:"flex",justifyContent:"space-between",gap:12,flexWrap:"wrap" }}><div><strong>{doc.model==="65"?"NFC-e":"NF-e"} · {statusLabel[doc.status]??doc.status}</strong><div className="muted" style={{ fontSize:10 }}>Criado {when(doc.created_at)} · ambiente {doc.environment}{doc.access_key?` · chave ${doc.access_key}`:""}</div>{doc.rejection_message?<div style={{ color:"#f97066",fontSize:11 }}>{doc.rejection_code?`${doc.rejection_code} · `:""}{doc.rejection_message}</div>:null}</div><strong style={{ color:statusColor[doc.status] }}>{statusLabel[doc.status]??doc.status}</strong></div>{job?<div className="muted" style={{ fontSize:10 }}>Job {job.job_type}: {job.status} · tentativas {job.attempts}/{job.max_attempts}{job.last_error?` · ${job.last_error}`:""}</div>:null}<div style={{ display:"flex",gap:8,flexWrap:"wrap" }}>{data.canIssue&&(doc.status==="draft"||doc.status==="rejected")?<QueueFiscalDocumentForm fiscalDocumentId={doc.id}/>:null}</div>{data.canCancel&&doc.status==="authorized"?<details><summary style={{ cursor:"pointer",fontSize:12,fontWeight:850 }}>Cancelar documento</summary><div style={{ marginTop:7,maxWidth:520 }}><CancelFiscalDocumentForm fiscalDocumentId={doc.id}/></div></details>:null}</div>; })}</article>
  </section>;
}
