import Link from "next/link";
import { cookies } from "next/headers";
import { redirect } from "next/navigation";
import type { InputHTMLAttributes, ReactNode } from "react";
import { PedeAquiLogo } from "@/components/brand/pedeaqui-brand";
import { reviewCheckoutAction, saveCheckoutAddressAction, saveCheckoutFulfillmentAction, saveCheckoutIdentityAction, saveCheckoutPaymentAction, useSavedCheckoutAddressAction } from "@/features/checkout/actions";
import { CheckoutReviewState, FinalOrderOptions, paymentMethodHelp } from "@/features/checkout/final-order-options";
import { applyCheckoutBenefitsAction, clearCheckoutBenefitsAction } from "@/features/growth/actions";
import { createOrderFromCheckoutAction } from "@/features/orders/actions";
import { cartCookieName } from "@/server/cart/cart-token";
import { CheckoutService } from "@/server/checkout/checkout-service";
import { paymentMethodLabels } from "@/server/checkout/schemas";
import { customerRecognitionCookieName } from "@/server/customers/recognition-token";
import { GrowthService } from "@/server/growth/growth-service";
import styles from "./checkout.module.css";

function money(cents: number) { return new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" }).format(cents / 100); }
const errorMessages: Record<string, string> = { cart_empty: "Seu carrinho está vazio.", invalid_phone: "Informe um telefone válido.", pickup_disabled: "Retirada não está disponível nesta loja.", delivery_disabled: "Entrega não está disponível nesta loja.", delivery_not_selected: "Escolha entrega antes de informar o endereço.", delivery_minimum: "O pedido ainda não atingiu o mínimo exigido para este bairro.", neighborhood_not_served: "Este bairro ainda não é atendido pela loja.", payment_unavailable: "A forma de pagamento selecionada não está disponível.", invalid_change: "O valor informado para troco precisa ser igual ou maior que o total.", checkout_not_ready: "O checkout precisa ser revisado novamente antes de criar o pedido.", benefit_invalid: "Não foi possível aplicar esses benefícios. Confira o cupom, o saldo disponível e a identificação do cliente.", saved_address_invalid: "Este endereço salvo não está mais disponível.", recognition_required: "Por segurança, informe o endereço novamente neste dispositivo.", identity_required: "Confirme seu nome e WhatsApp antes de reutilizar um endereço." };

export default async function CheckoutPage({ params, searchParams }: { params: Promise<{ slug: string }>; searchParams: Promise<{ erro?: string; revisar?: string }> }) {
  const { slug } = await params;
  const query = await searchParams;
  const cookieStore = await cookies();
  const token = cookieStore.get(cartCookieName(slug))?.value;
  if (!token) redirect(`/m/${slug}/carrinho`);
  const recognitionToken = cookieStore.get(customerRecognitionCookieName(slug))?.value ?? null;
  const reviewed = query.revisar === "1" ? await CheckoutService.review(slug, token, recognitionToken) : null;
  const data = reviewed ?? await CheckoutService.load(slug, token, recognitionToken);
  const benefits = await GrowthService.loadCheckoutBenefits(slug, token);
  const { cart, session, menu, recognizedCustomer } = data;
  const review = reviewed?.review ?? null;
  const enabledMethods = data.paymentMethods.filter((item) => item.enabled);
  const selectedPayment = session?.payment_method ?? null;
  const totalDiscount = Number(cart.discount_cents);
  const identityComplete = Boolean(session?.customer_name && session?.customer_phone_normalized);
  const fulfillmentComplete = Boolean(session?.fulfillment_type);
  const deliverySelected = session?.fulfillment_type === "delivery";
  const addressComplete = !deliverySelected || session?.delivery_quote_status === "valid";
  const paymentComplete = Boolean(selectedPayment);
  const recognizedForSession = Boolean(recognizedCustomer && session?.customer_id && session.customer_id === recognizedCustomer.customerId);
  const identityName = session?.customer_name ?? recognizedCustomer?.customer.name ?? "";
  const identityPhone = session?.customer_phone ?? recognizedCustomer?.customer.phone ?? "";
  const identityEmail = session?.customer_email ?? recognizedCustomer?.customer.email ?? "";

  return <main className={styles.root}><div className={styles.container}>
    <div className={styles.topbar}><Link href={`/m/${slug}/carrinho`} className={styles.back}>← Voltar ao carrinho</Link><PedeAquiLogo size="xs" decorative /></div>
    <header className={styles.header}><p className={styles.eyebrow}>Finalização</p><h1>Checkout</h1><p className="muted">Preencha somente o que se aplica ao seu pedido. Cada etapa é validada novamente no servidor.</p></header>
    <div className={styles.progress} aria-label="Etapas do checkout"><ProgressItem number="1" label="Identificação" done={identityComplete}/><ProgressItem number="2" label="Recebimento" done={fulfillmentComplete}/>{deliverySelected ? <ProgressItem number="3" label="Endereço" done={addressComplete}/> : null}<ProgressItem number={deliverySelected ? "4" : "3"} label="Pagamento" done={paymentComplete}/><ProgressItem number={deliverySelected ? "5" : "4"} label="Revisão" done={Boolean(review?.ready)}/></div>
    {query.erro ? <div role="alert" className={`card ${styles.alert}`}>{errorMessages[query.erro] ?? "Não foi possível salvar esta etapa. Revise os dados e tente novamente."}</div> : null}

    <section className={`card ${styles.section}`}><StepTitle number="1" title="Quem está pedindo?" complete={identityComplete}/>{recognizedCustomer && !identityComplete ? <p className="muted">Este dispositivo já foi usado em um pedido deste restaurante. Confira os dados preenchidos e salve a identificação para reutilizar seu endereço com segurança.</p> : null}<form action={saveCheckoutIdentityAction} className={styles.form}><input type="hidden" name="storeSlug" value={slug}/><div className={styles.grid2}><Field label="Nome" name="name" defaultValue={identityName} required/><Field label="Telefone / WhatsApp" name="phone" type="tel" defaultValue={identityPhone ?? ""} placeholder="(19) 99999-9999" required/></div><Field label="E-mail (opcional)" name="email" type="email" defaultValue={identityEmail ?? ""}/><ActionButton>Salvar identificação</ActionButton></form></section>

    <section className={`card ${styles.section}`}><StepTitle number="2" title="Como você quer receber?" complete={fulfillmentComplete}/><form action={saveCheckoutFulfillmentAction} className={styles.choices}><input type="hidden" name="storeSlug" value={slug}/>{menu.settings.allow_delivery && menu.delivery.enabled ? <button type="submit" name="fulfillmentType" value="delivery" className={`${styles.choice} ${deliverySelected ? styles.choiceSelected : ""}`}><span>Entrega</span><span className={styles.choiceDetail}>{menu.delivery.estimated_min_minutes}–{menu.delivery.estimated_max_minutes} min · endereço validado na próxima etapa</span></button> : null}{menu.settings.allow_pickup ? <button type="submit" name="fulfillmentType" value="pickup" className={`${styles.choice} ${session?.fulfillment_type === "pickup" ? styles.choiceSelected : ""}`}><span>Retirada</span><span className={styles.choiceDetail}>Você busca no estabelecimento; endereço de entrega não será solicitado</span></button> : null}</form></section>

    {deliverySelected ? <section className={`card ${styles.section}`}><StepTitle number="3" title="Onde devemos entregar?" complete={addressComplete}/>{recognizedForSession && recognizedCustomer && recognizedCustomer.addresses.length > 0 ? <div className={styles.form}><p className="muted">Você já pediu neste dispositivo. Confirme um endereço salvo ou informe outro abaixo.</p><div className={styles.choices}>{recognizedCustomer.addresses.map((address, index) => <form action={useSavedCheckoutAddressAction} key={`${address.postalCode}-${address.street}-${address.number}-${index}`}><input type="hidden" name="storeSlug" value={slug}/><input type="hidden" name="addressIndex" value={index}/><button type="submit" className={styles.choice}><strong>{address.isDefault ? "Endereço principal" : address.label}</strong><span className={styles.choiceDetail}>{address.street}, {address.number}{address.complement ? ` · ${address.complement}` : ""}<br/>{address.district} · {address.city}/{address.state} · CEP {address.postalCode}</span><span className={styles.choiceDetail}>Entregar neste endereço</span></button></form>)}</div></div> : recognizedCustomer && identityComplete && !recognizedForSession ? <div className={styles.deliveryError}>O telefone informado não corresponde ao cliente reconhecido neste dispositivo. Por segurança, nenhum endereço salvo foi exibido.</div> : null}<form action={saveCheckoutAddressAction} className={styles.form}><input type="hidden" name="storeSlug" value={slug}/><div className={styles.grid2}><Field label="CEP" name="postalCode" defaultValue={session?.address_postal_code ?? ""} required/><Field label="Bairro" name="district" defaultValue={session?.address_district ?? ""} required/></div><div className={styles.addressRow}><Field label="Rua" name="street" defaultValue={session?.address_street ?? ""} required/><Field label="Número" name="number" defaultValue={session?.address_number ?? ""} required/></div><Field label="Complemento (opcional)" name="complement" defaultValue={session?.address_complement ?? ""}/><div className={styles.grid2}><Field label="Cidade" name="city" defaultValue={session?.address_city ?? menu.store.city ?? ""} required/><Field label="UF" name="state" defaultValue={session?.address_state ?? menu.store.state ?? ""} maxLength={2} required/></div><Field label="Referência (opcional)" name="reference" defaultValue={session?.address_reference ?? ""}/>{session?.delivery_quote_status === "valid" ? <div className={styles.deliveryOk}>Entrega validada · {money(Number(session.delivery_fee_cents))} · {session.delivery_estimated_min_minutes}–{session.delivery_estimated_max_minutes} min</div> : session?.delivery_quote_status === "unserviceable" ? <div className={styles.deliveryError}>Este endereço não está apto para entrega com as regras atuais.</div> : null}<ActionButton>{recognizedForSession ? "Usar outro endereço e recalcular frete" : "Validar endereço e frete"}</ActionButton></form></section> : null}

    <section className={`card ${styles.section}`}><StepTitle number={deliverySelected ? "4" : "3"} title="Como você vai pagar?" complete={paymentComplete}/><form action={saveCheckoutPaymentAction} className={styles.form}><input type="hidden" name="storeSlug" value={slug}/>{enabledMethods.length === 0 ? <div className={styles.deliveryError}>Nenhuma forma de pagamento está habilitada para este estabelecimento no momento.</div> : <div className={styles.choices}>{enabledMethods.map((item) => <label key={item.method} className={`${styles.choice} ${selectedPayment === item.method ? styles.choiceSelected : ""}`}><span className={styles.paymentChoice}><input type="radio" name="paymentMethod" value={item.method} defaultChecked={selectedPayment === item.method} required/><strong>{paymentMethodLabels[item.method]}</strong></span><span className={styles.choiceDetail}>{paymentMethodHelp[item.method]}</span></label>)}</div>}{selectedPayment === "cash" ? <Field label="Troco para (opcional)" name="changeFor" inputMode="decimal" defaultValue={session?.cash_change_for_cents ? (Number(session.cash_change_for_cents) / 100).toFixed(2).replace(".", ",") : ""} placeholder="Ex.: 100,00"/> : null}{enabledMethods.length > 0 ? <ActionButton>Salvar pagamento</ActionButton> : null}</form></section>

    <details className={styles.optional} open={totalDiscount > 0}><summary>Benefícios opcionais — cupom, cashback e pontos{totalDiscount > 0 ? ` · economia ${money(totalDiscount)}` : ""}</summary><div className={styles.optionalBody}><p className="muted">O desconto é recalculado no servidor. Cashback e pontos dependem de cliente identificado e saldo elegível.</p><form action={applyCheckoutBenefitsAction} className={styles.form}><input type="hidden" name="storeSlug" value={slug}/><div className={styles.grid2}><Field label="Cupom" name="couponCode" defaultValue={benefits.current.couponCode ?? ""} placeholder="Ex.: VOLTA20"/><Field label={`Cashback${benefits.customerIdentified ? ` · saldo ${money(benefits.cashbackBalanceCents)}` : ""}`} name="cashbackAmount" inputMode="decimal" defaultValue={benefits.current.cashbackRedeemCents ? (benefits.current.cashbackRedeemCents / 100).toFixed(2).replace(".", ",") : ""} disabled={!benefits.cashbackEnabled || !benefits.customerIdentified}/><Field label={`Pontos${benefits.customerIdentified ? ` · saldo ${benefits.loyaltyBalancePoints}` : ""}`} name="loyaltyPoints" type="number" min={0} defaultValue={benefits.current.loyaltyRedeemPoints || ""} disabled={!benefits.loyaltyEnabled || !benefits.customerIdentified}/></div><div className={styles.benefitActions}><ActionButton>Aplicar benefícios</ActionButton>{totalDiscount > 0 ? <button formAction={clearCheckoutBenefitsAction} type="submit" className={styles.secondary}>Remover benefícios</button> : null}</div></form>{totalDiscount > 0 ? <div className={styles.benefitSummary}><strong>Economia total: {money(totalDiscount)}</strong>{benefits.current.couponDiscountCents > 0 ? <span>Cupom: − {money(benefits.current.couponDiscountCents)}</span> : null}{benefits.current.cashbackDiscountCents > 0 ? <span>Cashback: − {money(benefits.current.cashbackDiscountCents)}</span> : null}{benefits.current.loyaltyDiscountCents > 0 ? <span>Pontos: − {money(benefits.current.loyaltyDiscountCents)}</span> : null}</div> : null}</div></details>

    <section className={`card ${styles.review}`}><StepTitle number={deliverySelected ? "5" : "4"} title="Revise e confirme" complete={Boolean(review?.ready)}/><CheckoutReviewState reviewed={Boolean(review)} ready={Boolean(review?.ready)}/><FinalOrderOptions fulfillmentType={session?.fulfillment_type} address={{ street: session?.address_street, number: session?.address_number, district: session?.address_district }} deliveryMinutes={{ min: session?.delivery_estimated_min_minutes, max: session?.delivery_estimated_max_minutes }} paymentMethod={selectedPayment} cashChangeForCents={session?.cash_change_for_cents === null || session?.cash_change_for_cents === undefined ? null : Number(session.cash_change_for_cents)}/><div className={styles.summaryRows}><SummaryLine label="Subtotal" value={money(Number(cart.subtotal_cents))}/>{totalDiscount > 0 ? <SummaryLine label="Benefícios" value={`− ${money(totalDiscount)}`}/> : null}<SummaryLine label="Entrega" value={Number(cart.delivery_fee_cents) > 0 ? money(Number(cart.delivery_fee_cents)) : deliverySelected ? "Grátis" : "Não aplicável"}/><div className={styles.divider}/><SummaryLine label="Total" value={money(Number(cart.total_cents))} strong/></div>
      {review ? review.ready ? <div className={styles.reviewOk}><strong>Checkout validado.</strong><div>Dados, disponibilidade, entrega, pagamento e benefícios foram revalidados. Você já pode confirmar o pedido.</div></div> : <div className={styles.reviewError}><strong>Antes de criar o pedido:</strong><div className={styles.blockers}>{review.blockers.map((blocker) => <span key={blocker.code}>• {blocker.message}</span>)}</div></div> : null}
      {review?.ready ? <form action={createOrderFromCheckoutAction}><input type="hidden" name="storeSlug" value={slug}/><button type="submit" className={styles.finalAction}>Confirmar pedido</button></form> : <form action={reviewCheckoutAction}><input type="hidden" name="storeSlug" value={slug}/><button type="submit" className={styles.finalAction}>Revisar pedido</button></form>}
    </section>
  </div></main>;
}

function ProgressItem({ number, label, done }: { number: string; label: string; done: boolean }) { return <span className={`${styles.progressItem} ${done ? styles.progressDone : ""}`}><strong>{done ? "✓" : number}. {label}</strong><span>{done ? "Concluído" : "Pendente"}</span></span>; }
function StepTitle({ number, title, complete }: { number: string; title: string; complete: boolean }) { return <div className={styles.stepTitle}><span className={`${styles.stepBadge} ${complete ? styles.stepComplete : ""}`}>{complete ? "✓" : number}</span><h2>{title}</h2></div>; }
function Field(props: InputHTMLAttributes<HTMLInputElement> & { label: string }) { const { label, ...inputProps } = props; return <label className={styles.field}><span>{label}</span><input {...inputProps} className={styles.input}/></label>; }
function ActionButton({ children }: { children: ReactNode }) { return <button type="submit" className={styles.action}>{children}</button>; }
function SummaryLine({ label, value, strong = false }: { label: string; value: string; strong?: boolean }) { return <div className={`${styles.summaryLine} ${strong ? styles.total : ""}`}><span>{label}</span><strong>{value}</strong></div>; }
