"use client";

import { useActionState,useRef } from "react";
import {
  cancelManualFinanceAction,createFinanceAccountAction,createFinanceCategoryAction,createManualFinanceEntryAction,
  reverseFinanceSettlementAction,settleFinanceObligationAction,transferFinanceAction,type FinanceActionState,
} from "@/features/finance/actions";

const initial:FinanceActionState={ ok:false,message:null,error:null };
const inputStyle:React.CSSProperties={ minHeight:40,borderRadius:10,border:"1px solid var(--border)",background:"var(--surface-2)",color:"var(--text)",padding:"8px 10px",width:"100%" };
const buttonStyle:React.CSSProperties={ minHeight:40,border:0,borderRadius:10,background:"var(--accent)",color:"#fff",padding:"8px 12px",fontWeight:850,cursor:"pointer" };
function Feedback({ state }:{ state:FinanceActionState }) { if(state.error) return <div style={{ color:"#f97066",fontSize:12 }}>{state.error}</div>; if(state.message) return <div style={{ color:"#22c55e",fontSize:12 }}>{state.message}</div>; return null; }
type ServerAction=(previous:FinanceActionState,formData:FormData)=>Promise<FinanceActionState>;
function useIdempotentAction(serverAction:ServerAction){ const keyRef=useRef<string|null>(null); return useActionState(async(previous,formData)=>{ const key=keyRef.current??crypto.randomUUID(); keyRef.current=key; formData.set("idempotencyKey",key); const next=await serverAction(previous,formData); if(next.ok) keyRef.current=null; return next; },initial); }
function money(cents:number|string){ return (Number(cents||0)/100).toFixed(2).replace(".",","); }

type Account={ id:string;name:string;account_type:string;balance_cents:number|string };
type Category={ id:string;name:string;nature:string;dre_group:string;parent_id?:string|null };

export function FinanceAccountForm(){ const [state,action,pending]=useActionState(createFinanceAccountAction,initial); return <form action={action} style={{ display:"grid",gap:7 }}><input name="name" required minLength={2} maxLength={120} placeholder="Nome da conta" aria-label="Nome da conta financeira" style={inputStyle}/><select name="accountType" defaultValue="bank" aria-label="Tipo da conta" style={inputStyle}><option value="bank">Banco</option><option value="wallet">Carteira</option><option value="cash">Dinheiro</option><option value="clearing">Conta de liquidação</option><option value="other">Outra</option></select><button disabled={pending} style={buttonStyle}>{pending?"Salvando…":"Criar conta"}</button><Feedback state={state}/></form>; }

export function FinanceCategoryForm({ categories }:{ categories:Category[] }){ const [state,action,pending]=useActionState(createFinanceCategoryAction,initial); return <form action={action} style={{ display:"grid",gap:7 }}><input name="name" required minLength={2} maxLength={120} placeholder="Nome da categoria" aria-label="Nome da categoria financeira" style={inputStyle}/><div style={{ display:"grid",gridTemplateColumns:"1fr 1fr",gap:7 }}><select name="nature" defaultValue="expense" aria-label="Natureza" style={inputStyle}><option value="expense">Despesa</option><option value="revenue">Receita</option></select><select name="dreGroup" defaultValue="operating_expense" aria-label="Grupo da DRE" style={inputStyle}><option value="operating_expense">Despesa operacional</option><option value="other_expense">Outras despesas</option><option value="other_revenue">Outras receitas</option><option value="gross_revenue">Receita bruta</option><option value="deductions">Deduções</option><option value="delivery_revenue">Receita de entrega</option><option value="cogs">CPV</option></select></div><select name="parentId" defaultValue="" aria-label="Categoria pai" style={inputStyle}><option value="">Sem categoria pai</option>{categories.filter((c)=>!c.parent_id).map((c)=><option key={c.id} value={c.id}>{c.name}</option>)}</select><button disabled={pending} style={buttonStyle}>{pending?"Salvando…":"Criar categoria"}</button><Feedback state={state}/></form>; }

export function ManualFinanceEntryForm({ categories,accounts,today,canSettle }:{ categories:Category[];accounts:Account[];today:string;canSettle:boolean }){ const [state,action,pending]=useIdempotentAction(createManualFinanceEntryAction); return <form action={action} style={{ display:"grid",gap:8 }}><div style={{ display:"grid",gridTemplateColumns:"1fr 1fr",gap:7 }}><select name="direction" defaultValue="out" aria-label="Tipo de lançamento" style={inputStyle}><option value="out">Despesa / saída</option><option value="in">Receita / entrada</option></select><input name="amount" required inputMode="decimal" placeholder="Valor (R$)" aria-label="Valor do lançamento" style={inputStyle}/></div><select name="categoryId" required defaultValue="" aria-label="Categoria financeira" style={inputStyle}><option value="" disabled>Categoria</option>{categories.map((c)=><option key={c.id} value={c.id}>{c.name} · {c.nature==="revenue"?"receita":"despesa"}</option>)}</select><input name="description" required minLength={2} maxLength={300} placeholder="Descrição" aria-label="Descrição do lançamento" style={inputStyle}/><div style={{ display:"grid",gridTemplateColumns:"1fr 1fr",gap:7 }}><label><span className="muted" style={{ fontSize:10 }}>COMPETÊNCIA</span><input name="competenceDate" type="date" defaultValue={today} required style={inputStyle}/></label><label><span className="muted" style={{ fontSize:10 }}>VENCIMENTO</span><input name="dueDate" type="date" defaultValue={today} style={inputStyle}/></label></div>{canSettle?<select name="accountId" defaultValue="" aria-label="Liquidar imediatamente em conta" style={inputStyle}><option value="">Deixar em aberto</option>{accounts.map((a)=><option key={a.id} value={a.id}>Liquidar em {a.name} · saldo {money(a.balance_cents)}</option>)}</select>:null}<button disabled={pending} style={buttonStyle}>{pending?"Lançando…":"Criar lançamento"}</button><Feedback state={state}/></form>; }

export function SettleObligationForm({ obligationId,openCents,accounts }:{ obligationId:string;openCents:number|string;accounts:Account[] }){ const [state,action,pending]=useIdempotentAction(settleFinanceObligationAction); return <form action={action} style={{ display:"grid",gap:6 }}><input type="hidden" name="obligationId" value={obligationId}/><select name="accountId" required defaultValue="" aria-label="Conta para liquidação" style={inputStyle}><option value="" disabled>Conta</option>{accounts.map((a)=><option key={a.id} value={a.id}>{a.name}</option>)}</select><input name="amount" required inputMode="decimal" defaultValue={money(openCents)} aria-label="Valor da liquidação" style={inputStyle}/><div style={{ display:"grid",gridTemplateColumns:"1fr 1fr",gap:6 }}><input name="settledAt" type="datetime-local" aria-label="Data da liquidação" style={inputStyle}/><input name="reference" maxLength={120} placeholder="Referência" aria-label="Referência da liquidação" style={inputStyle}/></div><button disabled={pending} style={buttonStyle}>{pending?"Liquidando…":"Registrar liquidação"}</button><Feedback state={state}/></form>; }

export function ReverseSettlementForm({ transactionId }:{ transactionId:string }){ const [state,action,pending]=useIdempotentAction(reverseFinanceSettlementAction); return <form action={action} style={{ display:"grid",gap:6 }}><input type="hidden" name="transactionId" value={transactionId}/><input name="reason" required minLength={3} maxLength={500} placeholder="Motivo do estorno" aria-label="Motivo do estorno da liquidação" style={inputStyle}/><button disabled={pending} style={{ ...buttonStyle,background:"#b42318" }}>{pending?"Estornando…":"Estornar liquidação"}</button><Feedback state={state}/></form>; }

export function FinanceTransferForm({ accounts }:{ accounts:Account[] }){ const [state,action,pending]=useIdempotentAction(transferFinanceAction); return <form action={action} style={{ display:"grid",gap:7 }}><div style={{ display:"grid",gridTemplateColumns:"1fr 1fr",gap:7 }}><select name="sourceAccountId" required defaultValue="" aria-label="Conta de origem" style={inputStyle}><option value="" disabled>Origem</option>{accounts.map((a)=><option key={a.id} value={a.id}>{a.name}</option>)}</select><select name="targetAccountId" required defaultValue="" aria-label="Conta de destino" style={inputStyle}><option value="" disabled>Destino</option>{accounts.map((a)=><option key={a.id} value={a.id}>{a.name}</option>)}</select></div><input name="amount" required inputMode="decimal" placeholder="Valor (R$)" aria-label="Valor da transferência" style={inputStyle}/><div style={{ display:"grid",gridTemplateColumns:"1fr 1fr",gap:7 }}><input name="occurredAt" type="datetime-local" aria-label="Data da transferência" style={inputStyle}/><input name="reason" required minLength={3} maxLength={500} placeholder="Motivo / referência" aria-label="Motivo da transferência" style={inputStyle}/></div><button disabled={pending||accounts.length<2} style={buttonStyle}>{pending?"Transferindo…":"Transferir"}</button><Feedback state={state}/></form>; }

export function CancelManualFinanceForm({ obligationId }:{ obligationId:string }){ const [state,action,pending]=useIdempotentAction(cancelManualFinanceAction); return <form action={action} style={{ display:"grid",gap:6 }}><input type="hidden" name="obligationId" value={obligationId}/><input name="reason" required minLength={3} maxLength={500} placeholder="Motivo do cancelamento" aria-label="Motivo do cancelamento financeiro" style={inputStyle}/><button disabled={pending} style={{ ...buttonStyle,background:"var(--surface-3,#333)" }}>{pending?"Cancelando…":"Cancelar lançamento manual"}</button><Feedback state={state}/></form>; }
