"use client";

import { useActionState,useRef } from "react";
import { configureFiscalIntegrationAction,configureFiscalProfileAction,createFiscalDraftAction,createProductFiscalProfileAction,queueFiscalDocumentAction,requestFiscalCancelAction,type FiscalActionState } from "@/features/fiscal/actions";

const initial:FiscalActionState={ ok:false,message:null,error:null };
const field:React.CSSProperties={ minHeight:40,borderRadius:10,border:"1px solid var(--border)",background:"var(--surface-2)",color:"var(--text)",padding:"8px 10px",width:"100%" };
const button:React.CSSProperties={ minHeight:40,border:0,borderRadius:10,background:"var(--accent)",color:"#fff",padding:"8px 12px",fontWeight:850,cursor:"pointer" };
function Feedback({ state }:{ state:FiscalActionState }){ if(state.error) return <div style={{ color:"#f97066",fontSize:12 }}>{state.error}</div>; if(state.message) return <div style={{ color:"#22c55e",fontSize:12 }}>{state.message}</div>; return null; }
type ServerAction=(previous:FiscalActionState,formData:FormData)=>Promise<FiscalActionState>;
function useIdempotentAction(serverAction:ServerAction){ const ref=useRef<string|null>(null); return useActionState(async(previous:FiscalActionState,formData:FormData)=>{ const key=ref.current??crypto.randomUUID(); ref.current=key; formData.set("idempotencyKey",key); const next=await serverAction(previous,formData); if(next.ok) ref.current=null; return next; },initial); }

type Integration={ id:string;provider_key:string;name:string;environment:string;secret_ref:string|null;webhook_secret_ref:string|null };
type Profile={ integration_id:string|null;issuer_tax_id:string;state_registration:string|null;municipal_registration:string|null;crt_code:string|null;default_document_model:string;environment:string;certificate_ref:string|null;emission_policy:string };
type Product={ id:string;name:string;fiscalProfile:{ version:number;ncm:string|null;cest:string|null;default_cfop:string|null;cst_csosn:string|null;cclass_trib:string|null }|null };

export function FiscalIntegrationForm({ current }:{ current?:Integration|null }){ const [state,action,pending]=useActionState(configureFiscalIntegrationAction,initial); return <form action={action} style={{ display:"grid",gap:7 }}><input name="providerKey" required pattern="[a-z0-9][a-z0-9._-]+" defaultValue={current?.provider_key??""} placeholder="provider.exemplo" aria-label="Chave do provider" style={field}/><input name="name" required minLength={2} maxLength={120} defaultValue={current?.name??""} placeholder="Nome da integração" aria-label="Nome da integração fiscal" style={field}/><select name="environment" defaultValue={current?.environment??"homologation"} style={field} aria-label="Ambiente da integração"><option value="sandbox">Sandbox</option><option value="homologation">Homologação</option><option value="production">Produção</option></select><input name="secretRef" defaultValue={current?.secret_ref??""} placeholder="Referência do secret (ex.: FISCAL_TOKEN)" aria-label="Referência do token" style={field}/><input name="webhookSecretRef" defaultValue={current?.webhook_secret_ref??""} placeholder="Referência do secret do webhook" aria-label="Referência do secret do webhook" style={field}/><p className="muted" style={{ margin:0,fontSize:10 }}>Somente nomes/referências são persistidos. Tokens e certificados continuam fora do banco de domínio.</p><button disabled={pending} style={button}>{pending?"Salvando…":"Salvar integração"}</button><Feedback state={state}/></form>; }

export function FiscalProfileForm({ integrations,current }:{ integrations:Integration[];current?:Profile|null }){ const [state,action,pending]=useActionState(configureFiscalProfileAction,initial); return <form action={action} style={{ display:"grid",gap:7 }}><select name="integrationId" required defaultValue={current?.integration_id??integrations[0]?.id??""} style={field} aria-label="Integração fiscal"><option value="" disabled>Integração fiscal</option>{integrations.map((i)=><option key={i.id} value={i.id}>{i.name} · {i.environment}</option>)}</select><input name="issuerTaxId" required minLength={8} maxLength={32} defaultValue={current?.issuer_tax_id??""} placeholder="CNPJ / identificador fiscal" aria-label="Identificador fiscal do emissor" style={field}/><div style={{ display:"grid",gridTemplateColumns:"1fr 1fr",gap:7 }}><input name="stateRegistration" defaultValue={current?.state_registration??""} placeholder="Inscrição estadual" style={field}/><input name="municipalRegistration" defaultValue={current?.municipal_registration??""} placeholder="Inscrição municipal" style={field}/></div><div style={{ display:"grid",gridTemplateColumns:"1fr 1fr",gap:7 }}><input name="crtCode" defaultValue={current?.crt_code??""} placeholder="CRT" style={field}/><select name="documentModel" defaultValue={current?.default_document_model??"65"} style={field}><option value="65">NFC-e (65)</option><option value="55">NF-e (55)</option></select></div><div style={{ display:"grid",gridTemplateColumns:"1fr 1fr",gap:7 }}><select name="environment" defaultValue={current?.environment??"homologation"} style={field}><option value="homologation">Homologação</option><option value="production">Produção</option></select><select name="emissionPolicy" defaultValue={current?.emission_policy??"manual"} style={field}><option value="manual">Emissão manual</option><option value="on_payment">Após pagamento</option><option value="on_completion">Ao concluir pedido</option></select></div><input name="certificateRef" defaultValue={current?.certificate_ref??""} placeholder="Referência do certificado/secret" style={field}/><button disabled={pending||integrations.length===0} style={button}>{pending?"Salvando…":"Salvar perfil fiscal"}</button><Feedback state={state}/></form>; }

export function ProductFiscalProfileForm({ products }:{ products:Product[] }){ const [state,action,pending]=useActionState(createProductFiscalProfileAction,initial); return <form action={action} style={{ display:"grid",gap:7 }}><select name="productId" required defaultValue="" style={field}><option value="" disabled>Produto</option>{products.map((p)=><option key={p.id} value={p.id}>{p.name}{p.fiscalProfile?` · v${p.fiscalProfile.version}`:" · sem perfil"}</option>)}</select><input name="effectiveAt" type="datetime-local" style={field} aria-label="Vigência da classificação fiscal"/><div style={{ display:"grid",gridTemplateColumns:"1fr 1fr",gap:7 }}><input name="ncm" placeholder="NCM" style={field}/><input name="cest" placeholder="CEST" style={field}/></div><div style={{ display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:7 }}><input name="cfop" placeholder="CFOP" style={field}/><input name="cstCsosn" placeholder="CST/CSOSN" style={field}/><input name="cclassTrib" placeholder="cClassTrib" style={field}/></div><button disabled={pending||products.length===0} style={button}>{pending?"Criando…":"Criar nova versão fiscal"}</button><Feedback state={state}/></form>; }

export function CreateFiscalDraftForm({ orderId,model="65" }:{ orderId:string;model?:string }){ const [state,action,pending]=useIdempotentAction(createFiscalDraftAction); return <form action={action} style={{ display:"grid",gap:5 }}><input type="hidden" name="orderId" value={orderId}/><input type="hidden" name="documentModel" value={model}/><button disabled={pending} style={button}>{pending?"Criando…":`Criar ${model==="65"?"NFC-e":"NF-e"}`}</button><Feedback state={state}/></form>; }
export function QueueFiscalDocumentForm({ fiscalDocumentId }:{ fiscalDocumentId:string }){ const [state,action,pending]=useIdempotentAction(queueFiscalDocumentAction); return <form action={action} style={{ display:"grid",gap:5 }}><input type="hidden" name="fiscalDocumentId" value={fiscalDocumentId}/><button disabled={pending} style={button}>{pending?"Enfileirando…":"Enviar para emissão"}</button><Feedback state={state}/></form>; }
export function CancelFiscalDocumentForm({ fiscalDocumentId }:{ fiscalDocumentId:string }){ const [state,action,pending]=useIdempotentAction(requestFiscalCancelAction); return <form action={action} style={{ display:"grid",gap:5 }}><input type="hidden" name="fiscalDocumentId" value={fiscalDocumentId}/><input name="reason" required minLength={3} maxLength={500} placeholder="Motivo do cancelamento" style={field}/><button disabled={pending} style={{ ...button,background:"#b42318" }}>{pending?"Solicitando…":"Solicitar cancelamento"}</button><Feedback state={state}/></form>; }
